name: build_release
run-name: ${{ github.actor }} started building release

on:
  push:
    tags:
      - 'rc-0.0.*'

jobs:
  check_ts_lint:
    uses: ./.github/workflows/check_ts_lint.yml
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
